enabled_rules:
  - amp_script_in_head
  - boilerplate_in_head
  - contains_body_tag
  - contains_canonical_link
  - contains_head_tag
  - correct_a_href
  - correct_link
  - correct_meta
  - correct_script
  - doctype
  - meta_charset_first_in_head
  - meta_viewport_in_head
  - no_applet
  - no_audio
  - no_comments
  - no_embed
  - no_frame
  - no_frameset
  - no_i_amp_prefixed_attributes
  - no_iframe
  - no_img
  - no_inline_styles
  - no_object
  - no_on_attributes
  - no_param
  - no_xml_related_attributes
  - special_html_tag